apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
      - name: etherpad
        image: etherpad/etherpad:latest
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: etherpad-storage
          mountPath: /opt/etherpad-lite/var
        - name: etherpad-settings
          mountPath: /opt/etherpad-lite/settings.json
          subPath: settings.json
      volumes:
      - name: etherpad-storage
        persistentVolumeClaim:
          claimName: etherpad-pvc
      - name: etherpad-settings
        configMap:
          name: etherpad-settings
