apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad-mysql
  template:
    metadata:
      labels:
        app: etherpad-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: etherpad_db
        - name: MYSQL_USER
          value: etherpad_user
        - name: MYSQL_PASSWORD
          value: etherpad_password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etherpad-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: etherpad-mysql
