version: '3'

services:
  etherpad:
    image: etherpad/etherpad:latest
    container_name: etherpad
    environment:
      - ETHERPAD_DB_TYPE=mysql
      - ETHERPAD_DB_HOST=mysql
      - ETHERPAD_DB_USER=etherpad_user
      - ETHERPAD_DB_PASSWORD=etherpad_password
      - ETHERPAD_DB_NAME=etherpad_db
      - ETHERPAD_DB_CHARSET=utf8mb4
    volumes:
      - etherpad-data:/opt/etherpad-lite
    ports:
      - "9001:9001"
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: etherpad_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: etherpad_db
      MYSQL_USER: etherpad_user
      MYSQL_PASSWORD: etherpad_password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  etherpad-data:
  mysql-data: